### ISSUE TITLE
Change station and data source schemas to return only ids of species

### ISSUE THREAD

**Issue by ka7eh** [Oceans-1876/challenger-api#17]
Currently, both those objects return species with their full set of attributes, which makes their endpoints slow.

**Comment by Rashmil-1999** [comment]
So for this, we would need to either update the existing or create a new Object which will only return the list of ID of species. So we can add a new `SpeciesIDOnly` class which extends the `BaseModel` containing only id parameter and reference that in `DataSourceInDB`'s `species`'s list

**Comment by ka7eh** [comment]
> So for this, we would need to either update the existing or create a new Object which will only return the list of ID of species. So we can add a new `SpeciesIDOnly` class which extends the `BaseModel` containing only id parameter and reference that in `DataSourceInDB`'s `species`'s list

Let's try updating the existing schemas first. If we face a case that requires the current models' structures, we can include them later.

**Comment by Rashmil-1999** [comment]
I was talking about the schemas, where we can add a new schema for `Species` containing only `id`
