### ISSUE TITLE
Add tests for the new stations, species, and data source API endpoints.

### ISSUE THREAD

**Issue by ka7eh** [Oceans-1876/challenger-api#19]

**Comment by ojajegede** [comment]
Updated and added new tests to species, stations, and data_soruce. Able to get feedback from the pytests. Currently running into failures and programming errors dealing with the tests.

**Comment by ojajegede** [comment]
Added new tests, Still having issues/errors with tests(specifically run_tests.sh)

**Comment by ka7eh** [comment]
@ojajegede Are your changes ready for review? If so, can you make a PR for it and add the dev team as reviewer? Thanks.

**Comment by ojajegede** [comment]
Just created a PR @ka7eh
